apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/cch12313/rop-dex-frontend:latest
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: ghcr-secret

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          args: ["tunnel", "--no-autoupdate", "run"]
          volumeMounts:
            - name: cf-config
              mountPath: /etc/cloudflared/config.yaml
              subPath: rop-dex-config.yaml
              readOnly: true
            - name: cf-creds
              mountPath: /etc/cloudflared/rop-tunnel.json
              subPath: rop-tunnel.json
              readOnly: true
      volumes:
        - name: cf-config
          configMap:
            name: cloudflared-config
        - name: cf-creds
          secret:
            secretName: cloudflared-creds