name: Build and Deploy to GKE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: rop-dex
  GKE_CLUSTER: autopilot-cluster-1
  GKE_ZONE: us-west1
  DEPLOYMENT_NAME: frontend
  IMAGE: rop-dex-frontend

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./web
        platforms: linux/amd64
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE }}:latest
          ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE }}:${{ github.sha }}

    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

    - name: Deploy to GKE
      run: |
        # Update the deployment image
        kubectl set image deployment/$DEPLOYMENT_NAME \
          $DEPLOYMENT_NAME=ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE }}:${{ github.sha }}
        
        # Rollout restart to ensure new image is pulled
        kubectl rollout restart deployment/$DEPLOYMENT_NAME
        
        # Wait for rollout to complete
        kubectl rollout status deployment/$DEPLOYMENT_NAME --timeout=300s
        
        # Verify deployment
        kubectl get services -o wide